06_onlineshop/order/urls.py
from django.urls import path
from .views import *
app_name = 'orders'
urlpatterns = [
    path('create/', order_create, name='order_create'),
    path('create_ajax/', OrderCreateAjaxView.as_view(), name='order_create_ajax'),
    path('checkout/', OrderCheckoutAjaxView.as_view(), name='order_checkout'),
    path('validation/', OrderImpAjaxView.as_view(), name='order_validation'),
    path('complete/', order_complete, name='order_complete'),
    path('order_detail/<int:order_id>/', admin_order_detail,name='admin_order_detail'),
    path('order_pdf/<int:order_id>/', admin_order_pdf,name='admin_order_pdf'),
]

06_onlineshop/order/templates/order/create.html
{% extends 'base.html' %}

{% block title %}
Checkout
{% endblock %}

{% block script %}
<script type="text/javascript">
    csrf_token = '{{csrf_token}}';
    order_create_url = '{% url "orders:order_create_ajax" %}';
    order_checkout_url = '{% url "orders:order_checkout" %}';
    order_validation_url = '{% url "orders:order_validation" %}';
    order_complete_url = '{% url "orders:order_complete" %}';
</script>

<script src="https://cdn.iamport.kr/js/iamport.payment-1.1.8.js" type="text/javascript"></script>

{% load static %}
<script src="{% static 'js/checkout.js' %}" type="text/javascript"></script>
{% endblock %}

{% block content %}
<div class="row">
    <div class="col">
        <div class="alert alert-info" role="alert">Your Order</div>
        <ul class="list-group">
            {% for item in cart %}
                <li class="list-group-item">
                    {{item.quantity}}X{{item.product.name}}
                    <span>{{item.total_price}}</span>
                </li>
            {% endfor %}
            {% if cart.coupon %}
                <li class="list-group-item">
                    "{{cart.coupon.code}}" (${{cart.coupon.amount}} off)
                    <span>- ${{cart.get_total_discount|floatformat:"2"}}</span>
                </li>
            {% endif %}
        </ul>
        <div class="alert alert-success" role="alert">Total : {{cart.get_total_price|floatformat:"2"}}</div>
        <form action="" method="post" class="order-form">
            {{form.as_p}}
            {% csrf_token %}
            <input type="hidden" name="pre_order_id" value="0">
            <input type="hidden" name="amount" value="{{cart.get_total_price|floatformat:'2'}}">
            <input type="submit" class="btn btn-primary float-right" value="Place Order">
        </form>
    </div>
</div>
{% endblock %}

06_onlineshop/order/templates/order/created.html
{% extends 'base.html' %}

{% block title %}
Order Complete!
{% endblock %}

{% block content %}
<div class="row">
    <div class="col">
        <div class="alert alert-success" role="alert">Order #{{order.id}} is complete!</div>

    </div>
</div>
{% endblock %}